name: Flutter build and test
on: [ push ]
jobs:
  Build-And-Test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get dependencies
        run: |
          flutter pub get
          flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        run: flutter analyze
      - name: Appbundle build
        run: flutter build appbundle -t lib/main_prod.dart
      - name: iOS build
        run: flutter build ios --no-codesign -t lib/main_prod.dart
      - name: Test
        run: flutter test --coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info